---
# handlers file for configure-nfs
- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "restart firewalld"
- name: reload nfs
  command: 'exportfs -ra'
